# ProjectManager Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/syamn/ProjectManager

#==================#
#   Basic Config   #
#==================#
# No Configables Found!

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
Version: 0.1