##  Plugin Information  ##
name: ProjectManager
version: 0.2
main: syam.ProjectManager.ProjectManager
description: ProjectManager Plugin for SakuraServer
website: http://sakura-server.net/
depend: [WorldEdit]
softdepend: [dynmap]
##  Original Author     ##
author: syam
commands:
    project:
      usage: /project - to see the help
      aliases: [pj]
      description: To see the ProjectManager help.
permissions:
    pm.admin.create:
        default: op
        description: Allow create the new project
    pm.admin.delete:
        default: op
        description: Allow delete the project
    pm.admin.reload:
        default: op
        description: Allow reload the plugin config.yml
    pm.admin.editAllProject:
        default: op
        description: Allow management all project
    pm.admin.set.region:
        default: op
        description: Allow set project region config
    pm.admin.set.creative:
        default: op
        description: Allow set creative config
    pm.user.select:
        default: op
        description: Allow select the project
    pm.user.list:
        default: op
        description: Allow use list command
    pm.user.member:
        default: op
        description: Allow use member command
    pm.user.set:
        default: op
        description: Allow use set command